#ifndef DEFS_H
#define DEFS_H

/* GENERAL DEFINITIONS */

#define FALSE 0
#define TRUE 1

#define MAX_FILENAME 128
#define MAX_SIZE_DATAFIELD 5242880
#define MIN_SIZE_DATAFIELD 512
#define REGULAR_SIZE_DATAFIELD 131072

#define OK 1

#endif
